cd "C:\Users\Brian\Documents\nand2tetris\src\project03\Workspace"
copy "C:\Users\Brian\Documents\nand2tetris\src\project03\TestFiles\a\*.cmp"
copy "C:\Users\Brian\Documents\nand2tetris\src\project03\TestFiles\a\*.tst"
copy "C:\Users\Brian\Documents\nand2tetris\src\project03\TestFiles\b\*.cmp"
copy "C:\Users\Brian\Documents\nand2tetris\src\project03\TestFiles\b\*.tst"